export class InspectionDetails {
    InspectionID: number;
    InventoryID: number;
    ItemID: number;
    UserID?: number;
    QtyFailed: number;
    CompletedBy: number;
    CompletedByUser?: string
    CompletedDate: string
    CreatedBy: number;
    CreatedDate: string;
    POLineID: number;
    Qty: number;
    DateCode: number;
    PackagingID: number;
    CommodityID: number;
    ItemStatusID: number;
    PartNumber: string;
    PartNumberStrip: string;
    MfrName: string;
    PartDescription: string;
    WarehouseName: string;
    CustomerAccount: string;
    VendorAccount: string;
    CustomerAccountID: number;
    VendorAccountID: number;
    LotNumber: string;
    QCNotes: string;
    ItemQty: number;
    SalesOrderID: number;
    SOVersionID: number;
    PurchaseOrderID: number;
    POVersionID: number;
    ResultID: number;
    ExternalID?: string;
    poExternalID?: string;
    soExternalID?: string;
    inspectionTypeName: string;
    vendorType: string;
    answerPhotoCount: number;
    additionalPhotoCount: number;
}